/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mjava_io_SimpleInputStream */

#ifndef _Included_mjava_io_SimpleInputStream
#define _Included_mjava_io_SimpleInputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mjava_io_SimpleInputStream
 * Method:    hasnextLine
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_mjava_io_SimpleInputStream_hasnextLine
  (JNIEnv *, jobject);

/*
 * Class:     mjava_io_SimpleInputStream
 * Method:    readLine
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mjava_io_SimpleInputStream_readLine
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
