/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mjava_io_SimpleOutputStream */

#ifndef _Included_mjava_io_SimpleOutputStream
#define _Included_mjava_io_SimpleOutputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mjava_io_SimpleOutputStream
 * Method:    write
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_mjava_io_SimpleOutputStream_write
  (JNIEnv *, jclass, jcharArray);

#ifdef __cplusplus
}
#endif
#endif
